model_opts:
  model: NonVisualModel
  dataset: pie
  obs_input_type: [
    action, look, #nod, 
    hand_gesture, motion_direction,
    bbox,
    vehicle_act,
    num_lanes, intersection, traffic_light,
    traffic_direction, 
    #stop_sign,
    #ped_sign,
    #sign_present,
    ped_crossing,
    #signalized,
    #construction_sign,
    #road_type， 
    has_sign,   #替代效果更好
    #sign,
    #scene_density,
    group_size
]
  apply_class_weights: True
  normalize_boxes: False
  generator: True
  overlap: 0.6 
  
net_opts:
  num_hidden_units: 256
  num_heads: 8
  num_layers: 1
  dropout: 0.1

exp_opts:
  datasets: [pie]
  batch_size: [2]
  epochs: [100]
  lr: [5.0e-05]

  
data_opts:
  #fstride: 1
  #sample_type: all
  #subset: default
  #data_split_type: default
  seq_type: nonvisual
  data_opts:
  #fstride: 1
  #subset: default
  #data_split_type: default
  seq_type: nonvisual  
  #min_track_size: 76


