model_opts:
  model: NonVisualModel
  dataset: pie
  obs_input_type: ['behavior', 'bbox', 'vehicle_act', 'scene']
  apply_class_weights: True
  normalize_boxes: False
  generator: True
  
net_opts:
  num_hidden_units: 256
  num_heads: 8
  num_layers: 2
  dropout: 0.1
  
exp_opts:
  datasets: [pie]
  batch_size: [2]
  epochs: [30]
  lr: [5.0e-06]

  
data_opts:
  #fstride: 1
  #sample_type: all
  #subset: default
  #data_split_type: default
  seq_type: nonvisual
  data_opts:
  #fstride: 1
  #subset: default
  #data_split_type: default
  seq_type: nonvisual  
  #min_track_size: 76


